# Generated by Django 6.0.5 on 2026-06-24 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_subcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='subcategory',
        ),
    ]
